<?php

/**
 * Controller for refreshing all feed items. Will be executed
 * by javascript of the frontend and the cronjob (silent)
 *
 * @package    application_controllers
 * @copyright  Copyright (c) Tobias Zeising (http://www.aditu.de)
 * @license    GPLv3 (http://www.gnu.org/licenses/gpl-3.0.html)
 */
class UpdateController extends Zend_Controller_Action {

    /**
     * Initialize the controller
     *
     * @return void
     */
    public function init() {
        // suppress view rendering
        Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')->setNoRender(true);
    }
    

    /**
     * cronjob silent update
     *
     * @return void
     */
    public function silentAction() {
        // logging
        $logger = Zend_Registry::get('logger');
        $logger->log('start silent update', Zend_Log::DEBUG);
        
        // update feeds
        $updater = Zend_Controller_Action_HelperBroker::getStaticHelper('updater');
        
        // get all feeds
        $feedModel = new application_models_feeds();
        $feeds = $feedModel->fetchAll();
        
        $logger->log('update '.$feeds->count().' feeds', Zend_Log::DEBUG);
        $i = 1;
        foreach($feeds as $feed) {
            $logger->log('#'.$i++.' feed update', Zend_Log::DEBUG);
            $updater->feed($feed);
        }
        
        // set last update
        $settingsModel = new application_models_settings();
        $settingsModel->write('lastrefresh',Zend_Date::now()->get(Zend_Date::TIMESTAMP));
        
        // delete orphaned thumbnails
        $updater->cleanupThumbnails();
        $logger->log('delete orphaned thumbnails', Zend_Log::DEBUG);
        
        // optimize database
        application_models_base::optimizeDatabase();
        $logger->log('database successfully optimized', Zend_Log::DEBUG);
        
        $logger->log('finished silent update', Zend_Log::DEBUG);
    }
    
    
    /**
     * will be executed by the javascript ajax call
     * and signals that it finished successfully a complete
     * update using ajax
     *
     * @return void
     */
    public function finishAction() {
        $logger = Zend_Registry::get('logger');
        
        // set lastrefresh if timeout is already 0
        $updater = Zend_Controller_Action_HelperBroker::getStaticHelper('updater');
        if($updater->timeout()==0) {
        
            // save last refresh (current session will also be updated by models save)
            $lastrefresh = Zend_Date::now()->get(Zend_Date::TIMESTAMP);
            $settingsModel = new application_models_settings();
            $settingsModel->save(array(
                'lastrefresh' => $lastrefresh
            ));
            
            // delete orphaned thumbnails
            $updater->cleanupThumbnails();
            $logger->log('delete orphaned thumbnails', Zend_Log::DEBUG);
            
            // optimize database
            application_models_base::optimizeDatabase();
            $logger->log('database successfully optimized', Zend_Log::DEBUG);
            
            $logger->log('finished ajax update', Zend_Log::DEBUG);
        }
        
        // return new timeout and unread items
        $itemCounter = Zend_Controller_Action_HelperBroker::getStaticHelper('itemcounter');
        $this->_helper->json(
                array(
                    'timeout'      => $updater->timeout(),
                    'lastrefresh'  => isset($lastrefresh) ? $lastrefresh : Zend_Registry::get('session')->lastrefresh,
                    'categories'   => $itemCounter->unreadItemsCategories(),
                    'feeds'        => $itemCounter->unreadItemsFeeds()
                )
            );
    }
    
    
    /**
     * updates a given feed (for executing via ajax call)
     *
     * @return void
     */
    public function feedAction() {
        // timeout bigger than 0 = no feed refresh needed
        $updater = Zend_Controller_Action_HelperBroker::getStaticHelper('updater');
        if($updater->timeout()!=0) {
            $this->finishAction();
            return;
        }
        
        // get and check feed
        $feedModel = new application_models_feeds();
        $feeds = $feedModel->find($this->getRequest()->getParam('id'));
        
        if($feeds->count()==0)
            $this->_helper->json(array(
                'error' => $this->view->translate('No feed with given ID found')
            ));
        
        // update feed (fetch new data from source)
        $feed = $feeds->current();
        $result = $updater->feed($feed);
        
        // if necessary update icon
        $updateIcon = $feed->dirtyicon==1;
        if($updateIcon)
            $feedModel->saveIcon($feed);
        
        // create answer
        if(!is_numeric($result)) {
            $this->_helper->json(array(
                'error' => $result
            ));
        } else {
            // return category and feed unread items
            $this->_helper->json(
                array(
                    'success'       => true,
                    'icon'          => $updateIcon,
                    'lastrefresh'   => $result
                )
            );
        }
    }

    
    /**
     * reset the demo (only for reseting 
     * the demo on rsslounge.aditu.de)
     *
     * @return void
     */
    public function demoresetAction() {
        if(Zend_Registry::get('config')->demomode!="1") {
            die("only for rsslounge.aditu.de - you will destroy all your data with this action");
            exit();
            return;
        }
        
        // delete all files
        $folders = array(
            Zend_Registry::get('config')->thumbnails->path,
            Zend_Registry::get('config')->favicons->path,
            Zend_Registry::get('config')->rss->cache->path
        );
        
        foreach($folders as $folder) {
            $handle = opendir($folder);
            while ($file = readdir($handle)) {
                if($file != "." && $file != ".." && $file != '.htaccess') {
                    if(!is_dir($folder."/".$file))
                        unlink($folder."/".$file);
                }
            }
            closedir($handle);
        }

        // insert new database
        $sql = file_get_contents(APPLICATION_PATH . '/../updates/database-demo.sql');
        
        // execute (with new connection because of PDO::MYSQL_ATTR_USE_BUFFERED_QUERY Bug)
        $db = Zend_Registry::get('bootstrap')->getPluginResource('db')->getDbAdapter();
        $db = Zend_Db::factory('Pdo_Mysql', $db->getConfig());
        $db->getConnection();
        $db->exec($sql);

        // write icons
        file_put_contents(Zend_Registry::get('config')->favicons->path."0b832c11c1127f5bcf9011ebe7d98807.ico", base64_decode("AAABAAEAEBAAAAAAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAWAfamlgH2pBAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAWAfalNgH2r9YB9qtwAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAWEda0FgH2r3YB9q/2Afav9gH2pRAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAFjG22tYB9q/2Afav9gH2r/YB9qswAAAAEAAAABAAAAAQAAAAEAAAABHG0tJxxtLUEcbS11HG0tmxdyKXMuVz0LYxtts2Afav9gH2r/YB9q/2QfY7EAAAABAAAAAQAAAAEAAAABAAAAARxtLYccbS3/HG0t/xxtLf8bbi3/GXAqr1AxW39kG23/YB9q/2UfY/1SHn9THh3SSxod2H0dHdRNHR3UBwAAAAEcbS0ZHG0t5xxtLf8cbS3/HG0t/xhyKv8uVzyTZhdlyWcaYPlUH32XIR3Ooxod2f8dHdT/HR3U/x0d1McdHdRlAAAAARxtLW8cbS3/HG0t/xxtLf8Zbiz/GW0vyT5OhlNJPJRhKRvBmxkd2v8dHdT/HR3U/x0d1P8dHdT/HR3UywAAAAEZbS0FGG0tgRJuLdUWbS3TImwmvShwTVsVit/TGnncnx0d1qMeFdP/HR3U/x0d1P8dHdT/HR3Uzx0d1BcAAAABAAAAAQAAAAFKaSsZaWcqeYhkJquQZC2lRnaacwuS4HcKeNuFFznWpR8T088eF9TtHR3UsR0d1CEAAAABAAAAAQAAAAGSYygTnmIov5xiKP+ZYyj/oV8b/2t1W38Ap+fTAKvf/wCk3tUMb9pnGDTWFQAAAAEAAAABAAAAAQAAAAEAAAABl2MoaZVjKP+VYyj/lWMo/59fHP9afXKVAKbp7wCi3v8ApN7/AKvf9QGi3jMAAAABAAAAAQAAAAEAAAABAAAAAZVjKI2VYyj/lWMo/5VjKP+eXx3vO4ucVwCm6/UAot7/AKLe/wCi3v8Ao96DAAAAAQAAAAEAAAABAAAAAQAAAAGVYyiplWMo/5VjKP+VYyj5nl8dby6RqgUApurJAKLe/wCi3v8Aot7/AKLeeQAAAAEAAAABAAAAAQAAAAGVYygHlWMomZVjKJmVYyhtlWMoMwAAAAEAAAABAKbpLQCi3r0Aot7/AKLe/wCi3lMAAAABAAAAAQAAAAEAAAABlWMoA5VjKAUAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAKLeQwCi3q0Aot4/AAAAAQAAAAEAAAABAAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//w=="));
        file_put_contents(Zend_Registry::get('config')->favicons->path."9b0df61a6b6bde574e83b3b99f2da13c.ico", base64_decode("AAABAAMAMDAAAAEAGACoHAAANgAAACAgAAABABgAqAwAAN4cAAAQEAAAAQAYAGgDAACGKQAAKAAAADAAAABgAAAAAQAYAAAAAAAAAAAAEwsAABMLAAAAAAAAAAAAAAAAqAAApgAAqAAAqQAAqwAArAAArgAAsAAAsQAAswAAswAAtQAAtgAAtwAAuQAAugAAuwAAuwAAvAAAvQAAvgAAvgAAvgAAvgAAvgAAvgAAvgAAvgAAvQAAvQAAvAAAuwAAuQAAuAAAtwAAtQAAtAAAswAAsQAAsAAArwAArAAAqwAAqgAAqAAApwAApQAAqAAApgAAowAApQAApwAAqQAAqgAArAAArgAAsAAAsQAAswAAtAAAtgAAtwAAuAAAugAAugAAuwAAvAAAvgAAvgAAvgAAvgAAvgAAvwAAvgAAvgAAvgAAvQAAvAAAuwAAugAAuQAAtwAAtgAAtQAAswAAsgAAsAAArgAArAAAqwAAqQAAqAAApgAApAAAogAApQAAqAAApQAAqAAAqgAAqwAArQAArwAAsAAAswAAtAAAtgAAtwAAuQAAuwAAvAAAvQAAvgAAvwAAwAAAwQAAwgAAwgAAwgAAwgAAwwAAwgAAwgAAwgAAwQAAwAAAvwAAvgAAvQAAuwAAugAAuAAAtwAAtQAAswAAsQAAsAAArgAArAAAqgAAqAAApwAApQAApwAAqQAApwAAqgAArAAArQAAsAAAsgAAswAAtQAAtwAAuQAAugAAvAAAvgAAvwAAwQAAwgAAwwAAxAAAxQAAxQAAxQAAxgAAxgAAxwAAxgAAxQAAxQAAxAAAxAAAwgAAwQAAvwAAvgAAvAAAugAAuQAAtwAAtQAAtAAAsgAAsAAArgAArAAAqgAAqQAApgAAqAAAqwAAqQAArAAArgAArwAAsQAAtAAAtgAAtwAAuQAAuwAAvQAAvwAAwgAAwgAAxAAAxQAAxwAAxwAAyAAAyQAAyQAAygAAygAAygAAygAAyQAAyQAAyAAAxwAAxQAAxAAAwwAAwgAAvwAAvgAAvAAAugAAuAAAtwAAtAAAsgAAsAAArgAArAAAqwAAqAAAqQAArQAAqwAArgAAsAAAsgAAtAAAtgAAuAAAugAAvAAAvwAAwQAAwgAAxAAAxgAAyAAAyQAAygAAywAAzAAAzQAAzQAAzQAAzgAAzgAAzgAAzQAAzAAAzAAAygAAyQAAyAAAxgAAxQAAwwAAwQAAvwAAvQAAuwAAuAAAtgAAtQAAswAAsAAArgAArAAAqQAAqwAArwAArAAArwAAsQAAtAAAtgAAuQAAugAAvQAAvwAAwgAAxAAAxQAAyAAAyQAAywAAzAAAzgAAzwAA0AAA0QAA0QAA0QAA0gAA0QAA0QAA0QAA0AAAzwAAzgAAzAAAywAAygAAyAAAxgAAxAAAwgAAwAAAvgAAuwAAuQAAtwAAtAAAsgAAsAAArQAAqwAArQAAsAAArgAAsQAAswAAtgAAuAAAuwAAvQAAvwAAwgAAxQAAxgAAyQAAywAAzAAAzgAA0AAA0QAA0gAA1AAA1AAA1QAA1QAA1QAA1QAA1QAA1QAA1AAA0wAA0QAA0AAAzwAAzQAAzAAAyQAAxwAAxQAAwwAAwQAAvgAAvAAAuQAAtwAAtAAAsgAAsAAArAAArgAAsQAAsAAAswAAtgAAuAAAugAAvQAAwAAAwgAAxQAAxwAAyQAAzAAAzgAA0AAA0gAA1AAA1QAA1gAA1wAA2AAA2QAA2gAA2QAA2QAA2QAA2AAA2AAA1wAA1QAA1AAA0wAA0AAAzwAAzAAAygAAyAAAxQAAwwAAwQAAvgAAuwAAuQAAtwAAtAAAsQAArgAAsAAAswAAsgAAtQAAuAAAugAAvQAAwAAAwwAAxQAAyAAAygAAzQAAzwAA0gAA1AAA1QAA1wAA2QAA2gAA2wAA3AAA3QAA3QAA3QAA3QAA3QAA3AAA2wAA2gAA2QAA1wAA1gAA1AAA0gAA0AAAzQAAywAAyAAAxgAAwwAAwAAAvgAAugAAuAAAtgAAswAAsAAAsQAAtAAAswAAtwAAuQAAvAAAvwAAwgAAxQAAxwAAygAAzQAA0AAA0gAA1QAA1wAA2AAA2gAA3AAA3gAA3wAA4AAA4AAA4QAA4QAA4QAA4AAA4AAA3wAA3gAA3AAA2wAA2QAA1wAA1QAA0wAA0AAAzQAAywAAyAAAxQAAwgAAwAAAvQAAugAAtwAAtQAAsQAAsgAAtgAAtgAAuAAAuwAAvgAAwgAAxAAAxwAAygAAzQAA0AAA0gAA1QAA1wAA2gAA3AAA3gAA3wAA4QAA4gAA4wAA5AAA5QAA5QAA5AAA5AAA4wAA4wAA4gAA4AAA3gAA3AAA2wAA2AAA1gAA1AAA0AAAzgAAywAAyAAAxQAAwgAAvwAAvAAAugAAtwAAswAAtAAAtwAAtwAAugAAvQAAwAAAxAAAxgAAyQAAzAAA0AAA0wAA1gAA2AAA2wAA3QAA3wAA4gAA4wAA5QAA5gAA5wAA5wAA6AAA6AAA6AAA6AAA5wAA5gAA5QAA4wAA4gAA4AAA3gAA2wAA2QAA1gAA0wAA0AAAzQAAygAAxwAAxAAAwQAAvgAAuwAAuAAAtQAAtQAAuQAAuAAAuwAAvgAAwgAAxQAAyQAAzAAAzwAA0gAA1QEB1QUF0wMD0AIC0QIC1AIC1gIC1wMD2wMD4QAA6gAA6gAA7AAA7AAA6wAA6wAA6gEB5wYGzAcHwwIC2QAA4wAA4QAA3gAA2wAA2QAA1gAA0gcHuwgIrgICuwAAxgAAwgAAwAAAvAAAuQAAtgAAtwAAugAAugAAvgAAwQAAxAAAxwAAywAAzgAA0QAA0goKvh0dsDc2t0JCvT4+vD4+vT4+vz4+wENDxDY2wAwMyQAA7gAA7gAA7wAA7gAA7gAA6x0dw11cv2pqvTY2vAIC2AAA4wAA4AAA3gAA2wAA2BcXtFxct25utz08qwMDuAAAxQAAwgAAvgAAuwAAtwAAtwAAuwAAuwAAvgAAwgAAxQAAyQAAzAAAzxkZuGdnvMfG7vT0//X1//v5//v6//v6//v6//z7//n5//T0/8jJ7h8fwAAA8QAA8gAA8gAA7z09vurq+/v5//r5//n6/15fvwAA3wAA4wAA4AAA3ikpsNjY8vn5//r5//z7/3x8wwEBuwAAwwAAwAAAvAAAuAAAuQAAvAAAvQAAwAAAwwAAxwAAywAAyT8/r9fX8f///+3s/bi45J+f2pWV0ZeX0peX0peX05WV0paW1dLS9fX0/6+u4gMD3gAA9AAA9B4eyenp+fHv/7i46Lu66evs/9/e9xERwAAA5gAA4hISw9fX8+/u/7296Kqr2+bm//n5/x0dpQAAwQAAwQAAvgAAugAAugAAvQAAvgAAwgAAxQAAyAAAzE9Ptfz7//b1/6Gh2GlpxG5txnt7zXR0xnN0xnR0x3R0x3d3yWhoxXBwzOXl++Xk+hISzAAA9wIC55aV1f7+/8bF7l5dyVhXwt/f+e/t/SIiugAA5wEB3oOD0Pn4/9LR8V5dvWBfvcLC6v7//y0togEBvAAAwgAAvwAAuwAAuwAAvgAAvgAAwgAAxgAAySYmq/b1/vPy/4aFzWdnxLOy4OTk+Pv6///+//7+///+//r5//T0/9LS6V1dwtDQ8enp+xMTyAAA+To6wv7+/+vq/G5t0K+u42Niws/P8e/v+x8fugAA6SYmufT0//Hy/nh4x5ub05OT2aWl3f///yoqogABvgAAwwAAvwAAuwAAuwAAvwAAvwAAxAAAxwQEu6em1P///5mY0XBww+jo+fv6/+np/JSTznx7xnx8yHd2yJmZ1vHw/9jY7GRkxNXV8+np+BIS0AYG4M7N7f39/5eW2Xl50fX0/2VmwtHR8vPy+xgYvQQE27Cw3v7+/62t3G5uw+vr946O1qys4P///ysrowAAvwAAxAAAwAAAvAAAvAAAwAAAwAAAxAAAyCQkqvv8/9zd8Wlpv9fX7v///6Gh2xMTwQUF3gIC6QIC6wEB7xgY2dnZ7OPj8GZmxNjY9OPj8hQUzF9fyP///8/P7WZmzc/P7vb2/2RkwtbW8u/v9xQUvj49t////+fn92how8fH5/b2/4uL066u4P///ysrowEBwAAAxQAAwgAAvgAAvgAAwQAAwQAAxQEBx2Njuv///6en14iIyv///6+v1A8P0QAA5gAA6QAA7QAA8AAA8hYW4dPT6OTk72dmxdnY89nZ71lZxdvb8Pz8/nx905mZ2fv7//T0/WZmwtnZ8uHh8FRTv8PD4v///4aGzY6Oz/r6//Hx/I6O1LGx4P///ywspAEBwAAAxQAAwgAAvgAAvgAAwQAAwQAAxQUFxYODwP///4OCxK6v2v///0xMuAAA4wAA5wAA6gAA7gAA8QAA9BkZ4dbW6eTk8GhoxdTU7/Py/Ofm+P///7Gx4XBw0PHx+vj4/vj4/WhowtXV8PDw+uPj9/7//8XF5Wlpxenp9fb2+/X1/JCQ1LOz4P///ywspAEBwQAAxQAAwgAAvgAAvgAAwQAAwQAAxQgIxZaWy////3FxuLi32P///z09wwAA4wAA5wAA6gAA7gAA8QAA9BkZ4dbW6eXl8GlpxdXV7/39//79/+3s+Gtrz7+/5f////z8//v7/WlpwtbW7/r6/P39/+/v+HBwyLW23v////39/vn5/JGR1LW14f///ywspAEBwQAAxgAAwgAAvgAAvgAAwQAAwQAAxQYGxYqKwv///4ODwrGx2f///1JSuwAA5AAA5wAA6gAA7gAA8QAA9Boa4tXV6OTk8GpqxdjY8P7+/v///5CQ1YKC0f///8vL69LS6v///2lpwtjY7/v7+////52d1n19y////+bm883N5f7+/pOT1Le34P///ywspAEBwQAAxgAAwgAAvgAAvgAAwQAAwQAAxQICx2Zmt////66u2ZCQzf///7q63QcHyQAA5wAA6gAA7QAA8QAA9BQU29vb7+Tk8GpqxdjY7////9DQ62hozenp9fPz+jIyvo+Pyv///2lpwtjY7/7+/tra7mxsydnZ7v///0tLtXl5vP///5KS1Le34P///ywspAEBwQAAxgAAwgAAvgAAvgAAwQAAwQAAxQAAyTAwrv///+Li72xsv9zc7v///5mZ0g8PwgAA5QAA7AAA7gAA8wsL0ePj9uTk8Gpqxdvb8f///3Z2z6+v3////4qK0wEB6paWzP///2lpwtra8f///319zZqa1P///7Cw3gcHz3d3uP///5KS07e34P///ywspAEBwAAAxgAAwgAAvgAAvgAAwQAAwQAAxQAAyAcHusDA4P///6Cg0XR0wvPz+P///+fn9ZmZ1W1tvW9vvDAwtQsL093d8+Pj72lpxOXl9bGx33p6zv///+3t9xcXzwAA/KWl0v///2lpwejo9ru74nJyy/X1+vb2+igovwEB4YCAvf///5KS07e34P///ywspAEBwAAAxQAAwgAAvgAAvgAAwAAAwAAAxAAAxwAAyz4+s/39//7+/oqKyHBwws/P6Pz8/v///////////3x8vgoK0dra8uTk72xsxsDA53Bwz9zc8P///3Bw0QEB9gEB7qWl0f///21txMrK6nR0zcLC5f///4CAxwIC4AIC3oCAvP///5KS07e34P///ywsowEBvwAAxQAAwQAAvQAAvgAAvwAAvwAAwwAAxwAAygICy3Bwxf7+/v///6ys129vxHd3xn9/wYCAw5CQyjc3tAcH0tTU7Pn5/IeH0lhYy66u3v///9TU7RAQ3wAA+gEB7aur1f///5qa2lpaxZyc1f///+Tk8hUVwgAA5QQE2oCAvP///5KS07e34P///ywsowAAvwAAxAAAwAAAvAAAvAAAvgAAvgAAwwAAxgAAyQAAzQQEy2NjwO/v9////////8XF4Zub0JmZ0qOj2ExMuQAA5ZmZ1v///+bm8sLC5P///////0NDyAAA+AAA+AAA9Hd3y/////T0+cDA4f///////1ZWvwAA5gAA4wQE2ICAvP///5GR0re33////ywsowEBvgAAwwAAwAAAvAAAuwAAvQAAvgAAwgAAxQAAyQAAywAAzwMD0iwsvn5+v8jI4P///////////////6GhzQAA7hUVyb+/4P////////b2/mZm0QMD7wAA9gAA9gAA9RER2Kur2P////////39/3Z2zAYG3AAA5QAA4QQE14yMwP///66u5NDQ7////zU1pwICvwAAwgAAvgAAuwAAugAAvAAAvQAAwAAAwwAAxwAAygAAzgAA0QAA1QMD0xwczDw8yzs7tENDtEZGtyMjtwAA6wAA7hcX2klJxEZGtSIiyAIC8QAA9AAA9AAA9AAA8gAA8RUV40hIyUlJsycnvQQE4wAA5QAA4gAA3wEB2SMjrUdHry8vszY2rUhIqQwMqwAAwQAAwQAAvgAAugAAugAAuwAAuwAAvwAAwgAAxQAAyAAAzAAAzwAA0wAA1gAA2QAA3AAA3wAA4gAA5AAA5wAA6QAA6wAA7QAA7gAA7wAA8AAA8QAA8QAA8QAA8QAA8AAA7wAA7QAA7AAA6QAA6AAA5QAA4gAA4AAA3QAA2gAA1wAA1AAA0AAAzQAAyQAAxgAAwwAAvwAAvAAAuQAAuQAAugAAugAAvQAAwAAAwwAAxwAAygAAzQAA0AAA1AAA1wAA2gAA3QAA4AAA4gAA5QAA5wAA6QAA6gAA7AAA7QAA7QAA7gAA7gAA7gAA7QAA7AAA7AAA6wAA6QAA5gAA5QAA4wAA4AAA3gAA2wAA1wAA1AAA0QAAzgAAywAAxwAAxAAAwgAAvgAAugAAtwAAuAAAuQAAuAAAvAAAvgAAwgAAxQAAyAAAywAAzgAA0QAA1AAA1wAA2gAA3QAA3wAA4QAA4wAA5gAA5wAA6AAA6QAA6gAA6wAA6gAA6gAA6gAA6QAA6QAA5wAA5gAA5AAA4gAA4AAA3gAA2wAA2AAA1QAA0gAAzwAAzAAAyQAAxgAAwgAAwAAAvAAAugAAtgAAtwAAtwAAtwAAugAAvQAAwAAAwgAAxgAAyQAAzAAAzwAA0gAA1AAA1wAA2gAA3AAA3gAA4QAA4gAA5AAA5QAA5gAA5gAA5wAA5wAA5wAA5wAA5gAA5gAA5AAA4gAA4QAA3wAA3QAA2gAA2AAA1QAA0gAA0AAAzQAAyQAAxgAAxAAAwQAAvgAAugAAuAAAtAAAtQAAtgAAtQAAuAAAvAAAvgAAwQAAxAAAxwAAyQAAzAAA0AAA0gAA1QAA1wAA2QAA2wAA3gAA3gAA4AAA4gAA4gAA4wAA5AAA4wAA5AAA4wAA4gAA4gAA4AAA3wAA3gAA3AAA2QAA1wAA1QAA0gAA0AAAzQAAygAAxwAAxAAAwgAAvwAAvAAAuQAAtgAAswAAtAAAtQAAswAAtwAAugAAvAAAvwAAwgAAxAAAxwAAygAAzAAAzwAA0QAA1AAA1gAA2AAA2gAA2wAA3QAA3gAA3wAA3wAA4AAA4AAA4AAA4AAA3wAA3gAA3QAA3AAA2gAA2AAA1wAA1AAA0gAA0AAAzQAAygAAyAAAxQAAwgAAwAAAvQAAugAAtwAAtAAAsQAAswAAswAAsgAAtQAAuAAAugAAvQAAvwAAwgAAxQAAxwAAyQAAzAAAzgAA0AAA0wAA1AAA1wAA2AAA2QAA2wAA2wAA3AAA3AAA3AAA3AAA3AAA2wAA2wAA2gAA2AAA1gAA1QAA0wAA0QAAzwAAzAAAygAAxwAAxQAAwgAAvwAAvQAAugAAuAAAtQAAswAAsAAAsQAAsQAAsAAAswAAtgAAuAAAugAAvgAAvwAAwgAAxAAAxwAAyQAAywAAzQAAzwAA0QAA0wAA1AAA1gAA1gAA1wAA1wAA2AAA2AAA2AAA2AAA1wAA1wAA1gAA1AAA0wAA0gAA0AAAzQAAzAAAyQAAxwAAxQAAwgAAwAAAvQAAuwAAuAAAtgAAswAAsQAArgAAsAAAsAAArwAAsgAAtAAAtgAAuAAAuwAAvgAAvwAAwgAAxAAAxgAAyAAAygAAzAAAzgAAzwAA0QAA0gAA0wAA1AAA1AAA1QAA1AAA1QAA1AAA1AAA0wAA0gAA0AAA0AAAzgAAzAAAywAAyQAAxgAAxAAAwgAAwAAAvgAAuwAAuQAAtgAAswAAsQAAsAAArAAArgAArwAArQAAsAAAsgAAtAAAtwAAuAAAuwAAvQAAvwAAwgAAwwAAxQAAxwAAyQAAywAAzAAAzQAAzgAAzwAA0AAA0AAA0AAA0QAA0AAA0AAA0AAA0AAAzgAAzQAAzAAAygAAyQAAxwAAxQAAwwAAwQAAvwAAvQAAugAAuQAAtgAAtAAAsgAAsAAArQAAqwAArQAArAAArAAArgAAsAAAsgAAtAAAtgAAuAAAuwAAvAAAvgAAwQAAwgAAxAAAxgAAxwAAyQAAygAAywAAywAAzAAAzAAAzQAAzQAAzQAAzAAAzAAAywAAygAAygAAyQAAxwAAxQAAxAAAwgAAwAAAvgAAvAAAugAAuAAAtgAAtAAAsgAAsAAArQAArAAAqQAArAAArAAAqQAArAAArgAAsAAAsgAAtAAAtwAAuAAAugAAvQAAvgAAwAAAwgAAwwAAxAAAxQAAxgAAxwAAyAAAyQAAyQAAyQAAyQAAyQAAyQAAyAAAyAAAxwAAxgAAxQAAxAAAwgAAwQAAvwAAvgAAvAAAugAAuAAAtgAAswAAsgAAsAAArgAArAAAqgAAqAAAqwAAqgAApwAAqgAArAAArgAAsAAAsgAAtAAAtgAAuAAAugAAuwAAvgAAvwAAwAAAwgAAwgAAxAAAxAAAxAAAxQAAxQAAxQAAxQAAxQAAxQAAxQAAxAAAwwAAwgAAwgAAwAAAvgAAvgAAuwAAugAAuQAAtwAAtQAAswAAsQAAsAAArgAArAAAqgAAqAAApgAAqgAApwAApQAAqAAAqQAArAAArgAAsAAAsQAAswAAtQAAtwAAuQAAugAAuwAAvQAAvgAAvwAAvwAAwAAAwAAAwQAAwQAAwQAAwQAAwQAAwQAAwAAAwAAAvwAAvgAAvgAAvAAAuwAAugAAuAAAtwAAtQAAswAAsgAAsAAArgAArQAAqwAAqQAApwAApgAApAAAqAAAqQAApwAAqgAArAAArgAArwAAsQAAswAAtQAAtwAAuAAAugAAuwAAvQAAvgAAvgAAvwAAvwAAwAAAwAAAwAAAwQAAwQAAwAAAwQAAwAAAwAAAvwAAvwAAvgAAvQAAvAAAuwAAugAAuAAAtwAAtgAAtAAAswAAsgAAsAAArgAArAAAqwAAqgAAqQAApwAAqwAAAAAAAFMAAAAAAAAAVAAAAAAAAABVAAAAAAAAAFYAAAAAAAAAWAAAAAAAAABZAAAAAAAAAFoAAAAAAAAAWwAAAAAAAABcAAAAAAAAAF0AAAAAAAAAXwAAAAAAAABgAAAAAAAAAGEAAAAAAAAAYgAAAAAAAABjAAAAAAAAAGQAAAAAAAAAZgAAAAAAAABnAAAAAAAAAGgAAAAAAAAAaQAAAAAAAABqAAAAAAAAAGwAAAAAAAAAbQAAAAAAAABuAAAAAAAAAG8AAAAAAAAAcAAAAAAAAABxAAAAAAAAAHMAAAAAAAAAdAAAAAAAAAB1AAAAAAAAAHYAAAAAAAAAdwAAAAAAAAB4AAAAAAAAAHoAAAAAAAAAewAAAAAAAAB8AAAAAAAAAH0AAAAAAAAAfgAAAAAAAAB/AAAAAAAAAIEAAAAAAAAAggAAAAAAAACDAAAAAAAAAIQAAAAAAAAAhQAAAAAAAACHAAAAAAAAAIgAAAAAAAAAiQAAAAAAAACKACgAAAAgAAAAQAAAAAEAGAAAAAAAAAAAABMLAAATCwAAAAAAAAAAAAAAAK0AAKgAAKwAAK4AALEAALMAALUAALcAALkAALoAAL0AAL4AAL4AAMAAAMAAAMEAAMEAAMAAAMAAAL8AAL4AALwAALoAALgAALcAALQAALIAALAAAK0AAKsAAKcAAKwAAKgAAKQAAKgAAKsAAK0AALAAALMAALUAALcAALoAALsAAL0AAL4AAL8AAMAAAMAAAMEAAMAAAL8AAL4AAL0AALsAALkAALcAALQAALEAAK8AAKwAAKkAAKcAAKMAAKgAAKwAAKgAAKwAALAAALMAALUAALgAALoAAL0AAMAAAMIAAMQAAMUAAMYAAMcAAMcAAMcAAMcAAMYAAMUAAMMAAMEAAL8AALwAALoAALcAALQAALEAAK4AAKsAAKcAAKsAAK8AAKsAALAAALMAALYAALkAALwAAL8AAMIAAMUAAMcAAMkAAMoAAMwAAMwAAM0AAMwAAMwAAMsAAMoAAMgAAMYAAMQAAMEAAL4AALoAALcAALQAALEAAK4AAKoAAK0AALEAAK4AALMAALcAALoAAL0AAMEAAMQAAMcAAMoAAMwAAM4AANAAANIAANIAANMAANIAANIAANEAAM8AAM0AAMsAAMkAAMUAAMIAAL8AALsAALgAALQAALEAAKwAALAAALMAALAAALYAALoAAL4AAMEAAMUAAMgAAMwAAM8AANEAANQAANYAANcAANgAANgAANgAANcAANcAANUAANMAANAAAM0AAMoAAMcAAMMAAL8AALsAALgAALQAAK8AALIAALYAALMAALkAAL0AAMEAAMUAAMkAAM0AANEAANQAANcAANkAANsAAN0AAN4AAN4AAN4AAN4AANwAANoAANgAANUAANIAAM8AAMsAAMcAAMMAAL8AALoAALcAALEAALQAALgAALYAALsAAMAAAMUAAMkAAM0AANEAANUAANgAANsAAN4AAOEAAOIAAOMAAOQAAOQAAOMAAOIAAOAAAN0AANoAANcAANMAAM8AAMsAAMcAAMIAAL4AALoAALQAALYAALoAALgAAL4AAMMAAMgAAMwAANEAANUAANkAAN0AAOEAAOMAAOYAAOgAAOkAAOkAAOkAAOgAAOcAAOUAAOIAAN8AANsAANcAANQAAM8AAMoAAMUAAMEAALwAALYAALgAALwAALsAAMEAAMYAAMsAANABAcwREbwjI7shIbkhILwhIL0nJsQNDc4AAO0AAO4AAO4AAO0bG8U4OLMTE8IAAOMAAN8AANsBAdAqKbA1NaUGBrIAAMMAAL4AALgAALoAAL4AAL0AAMMAAMgAAM4rK7SjotTj4/Xg4Pfk5P3k4/zk4/zs6//e3vUeHr8AAPIAAPI5Ob7y8f/4+P/e3vUREb0AAOMAANpra7719f/5+P+wsNsDA7YAAMEAALoAALsAAL8AAL8AAMUAAMtKSrL5+P+4uOOIiM+Fhc+CgsmCgsp/f8t2d8rd3faNjdMAAPYKCtPt7f25uehyccv09P9MTLsAAOYwMLv9/P+RkdGKis76+f8XF6QAAMMAALwAAL0AAMEAAMEAAMcgIKj//v+Xl9KVldPo5/rp6fji4fPk4/Tx8f2dndSrq+CYmNUAAPWDg87q6vmKiteDg83g4PhGRrgDA9nLyunBwuaOjs6Wltnq6voXF6QAAMQAAL4AAL4AAMIAAMIBAcWiodHIyOeYmNH+/v9bW8AcHMoYGNUYGNenp921tdyysuKHh84nJ8f///+Pj9fLy+yZmdPg4PY9PLdOTrv9/f+Fhc3f3/SZmdns7PoXF6UAAMYAAL8AAL8AAMMAAMMVFbvl5vCYmNDy8vpZWboAAOYAAOsAAPAAAPSNjde6ut2srN67u+PExOXFxemWltj+/v+UlNDT0+6ZmdPm5fOhode5ueD39/+Zmdju7voXF6YAAMcAAMAAAMAAAMMAAMMmJrzr6/KMjcX29fojI8YAAOYAAOsAAPAAAPSSkti7u92np9v////4+P2Dg9Tw7/n///+Xl9DR0ev////S0uqNjc/////29vudndjx8foXF6YAAMcAAMAAAMAAAMMAAMMfH7rt7fOXl8z+/v47O7wAAOYAAOsAAPAAAPSVldu7u92qqtv///+goNm+vuTHx+XU1OmentPW1uz9/f2KidHj4/G2ttrm5vGgoNnz8/oXF6YAAMcAAMAAAMAAAMMAAMMGBr/Pz+W2ttvDw+LT0+gTE70AAOcAAO4AAPONjdO9vd6wsN7f3/GSktb///8hIcSmptOkpNXe3vCyst6wsN3Y2O4lJbXh4e2jo9rz8/oXF6YAAMcAAMAAAMAAAMIAAMIAAMlYWLT///+GhsfV1er7+/+srNiYmMsmJrt8fMy7u92rq9uVldbs7PaBgdABAfO8vNumptXAwOWOjtP///89PcAQEMft7fKjo9rz8/oXF6YAAMYAAL8AAMAAAMIAAMIAAMgGBsK3t+Dx8fWSks6amtKvr9bBweAmJrd1dcfd3fBwcMy9veT19foREd4AAPbHx+G/v+R1dcvi4vK1tdwBAd8WFsTu7vOiotnz8/oXF6QAAMUAAL4AAL8AAMAAAMAAAMYAAMwMDMSWltb39/ji4u3IyOPQ0OkqKrUsLLz////r6/b///9QUMsAAPgAAPV6esz////y8vn19fsbG8EAAOMaGsD///+3t+T///8dHaYAAMQAAL4AAL4AAL8AAL4AAMUAAMoAAM8BAdMfH75lZc53d8J+fsUeHrgAAO5LS81+fsdAQMwBAfMAAPQAAPQJCeRra9J2dsEoKMwAAOUAAOELC8Rvb7pVVbtxcbkNDa0AAMIAALwAAL0AAL0AALwAAMIAAMcAAMwAANEAANYAANsAAN8AAOMAAOcAAOoAAO0AAO8AAPAAAPEAAPAAAO8AAO4AAOwAAOgAAOUAAOEAAN0AANgAANQAAM8AAMoAAMUAAMAAALoAALsAALsAALoAAMAAAMUAAMkAAM4AANMAANcAANsAAN8AAOIAAOYAAOgAAOoAAOsAAOwAAOsAAOoAAOkAAOcAAOQAAOEAAN4AANoAANUAANAAAMwAAMcAAMIAAL4AALcAALkAALoAALgAAL4AAMIAAMYAAMsAAM8AANQAANcAANsAAN4AAOEAAOMAAOUAAOYAAOYAAOYAAOYAAOQAAOIAAOAAAN0AANkAANUAANEAAM0AAMkAAMQAAL8AALoAALUAALcAALcAALUAALoAAL8AAMMAAMcAAMsAAM8AANMAANYAANkAANwAAN4AAN8AAOEAAOEAAOEAAOAAAN8AAN0AANsAANcAANQAANEAAM0AAMkAAMUAAMEAALwAALgAALMAALUAALUAALMAALcAALwAAL8AAMMAAMcAAMoAAM4AANEAANQAANcAANkAANoAANsAANsAANsAANsAANkAANcAANUAANMAANAAAMwAAMkAAMUAAMEAAL0AALkAALUAALAAALMAALMAALAAALUAALgAALwAAL8AAMMAAMYAAMkAAMwAANAAANEAANMAANQAANUAANYAANUAANUAANQAANIAANAAAM0AAMsAAMgAAMQAAMEAAL4AALoAALYAALIAAK0AALEAALAAAK0AALIAALUAALgAALwAAL8AAMIAAMUAAMgAAMoAAMwAAM4AAM8AANAAANAAANAAAM8AAM4AAMwAAMsAAMgAAMYAAMMAAMAAAL0AALkAALYAALMAALAAAKsAAK8AAK4AAKoAAK8AALIAALUAALgAALsAAL4AAMEAAMQAAMUAAMcAAMkAAMkAAMoAAMoAAMoAAMkAAMgAAMcAAMUAAMMAAMEAAL4AALwAALkAALYAALMAALAAAK0AAKgAAK0AAKoAAKYAAKsAAK4AALEAALMAALcAALoAALwAAL4AAMAAAMIAAMIAAMIAAMMAAMMAAMMAAMMAAMIAAMAAAL8AAL0AALsAALgAALYAALMAALEAAK4AAKsAAKgAAKQAAKoAAK4AAKoAAK4AALEAALQAALcAALkAALsAAL4AAMAAAMEAAMIAAMIAAMIAAMMAAMMAAMMAAMIAAMIAAMEAAL8AAL4AALwAALoAALgAALYAALMAALEAAK8AAKwAAKkAAK8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAQAAAAIAAAAAEAGAAAAAAAAAAAABMLAAATCwAAAAAAAAAAAAAAAMoAAMcAAMwAAM8AANIAANQAANYAANcAANcAANYAANQAANEAAM4AAMsAAMcAAMoAAMgAAMYAAMsAAM8AANMAANYAANgAANoAANkAANgAANYAANIAAM4AAMoAAMUAAMcAAMwAAMwAANIAANcAANsAAN8AAOEAAOMAAOIAAOEAAN4AANoAANUAANAAAMoAAMsAANAAANAAANcAAN0AAOIAAOYAAOkAAOoAAOoAAOgAAOUAAOEAANsAANYAAM4AAM4AANMAANQCAtodHb85OcU5OcYvL8oCAu4DA+xCQckUFM0AAOcgILwwL7YDA8cAANEAANUAANdLS8mtrdvCwuW2tt+6uuMVFdMqKsnU0+1cXMAGBtSjotWzs9sfH7EAANQAANceHrXV1eynpt5cXM2HhtXAwOVKSsCbm9a2tuRzc8ZkZMLCwuq2tuIzM7MAANUAANhra8nX1+ckJNUAAPM7O97ExODPz+vKyuzLy+fGxuTCweTe3vK/v+MuLrMAANYAANhdXcLl5fA5OcIBAeouLsnNzejR0eubmtSmptXR0eu1tN+iotTHx+UvL7QAANYAANcUFMPFxePU1OePj8lUVLvAwOLMzOshIcyams/V1exOTsFWVsDm5vIyMrIAANYAANYAANgfH8yEhNSVldMpKcmTk9tMTM8AAPlfX8yRkdkFBeE/P7+bm9UjI7UAANQAANQAANUAAN0AAOQAAOoAAO4AAPIAAPQAAPMAAPEAAO0AAOgAAOIAANsAANMAANIAANEAANEAANgAAN4AAOQAAOgAAOsAAOwAAOwAAOoAAOcAAOIAAN0AANcAAM8AAM8AAM0AAM0AANMAANgAAN0AAOEAAOMAAOUAAOQAAOMAAOAAANwAANcAANIAAMsAAMwAAMkAAMcAAM0AANIAANYAANkAANoAANsAANsAANoAANcAANQAANAAAMsAAMYAAMgAAMsAAMkAAM4AANIAANUAANcAANgAANgAANgAANcAANUAANMAANAAAMwAAMgAAMsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgpAAAAAA"));
        file_put_contents(Zend_Registry::get('config')->favicons->path."78ae7a488905806a06facd735c3d73b9.ico", base64_decode("AAABAAEAEBAAAAEACABoBQAAFgAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAD///8AzP//AJn//wBm//8AM///AAD//wD/zP8AzMz/AJnM/wBmzP8AM8z/AADM/wD/mf8AzJn/AJmZ/wBmmf8AM5n/AACZ/wD/Zv8AzGb/AJlm/wBmZv8AM2b/AABm/wD/M/8AzDP/AJkz/wBmM/8AMzP/AAAz/wD/AP8AzAD/AJkA/wBmAP8AMwD/AAAA/wD//8wAzP/MAJn/zABm/8wAM//MAAD/zAD/zMwAzMzMAJnMzABmzMwAM8zMAADMzAD/mcwAzJnMAJmZzABmmcwAM5nMAACZzAD/ZswAzGbMAJlmzABmZswAM2bMAABmzAD/M8wAzDPMAJkzzABmM8wAMzPMAAAzzAD/AMwAzADMAJkAzABmAMwAMwDMAAAAzAD//5kAzP+ZAJn/mQBm/5kAM/+ZAAD/mQD/zJkAzMyZAJnMmQBmzJkAM8yZAADMmQD/mZkAzJmZAJmZmQBmmZkAM5mZAACZmQD/ZpkAzGaZAJlmmQBmZpkAM2aZAABmmQD/M5kAzDOZAJkzmQBmM5kAMzOZAAAzmQD/AJkAzACZAJkAmQBmAJkAMwCZAAAAmQD//2YAzP9mAJn/ZgBm/2YAM/9mAAD/ZgD/zGYAzMxmAJnMZgBmzGYAM8xmAADMZgD/mWYAzJlmAJmZZgBmmWYAM5lmAACZZgD/ZmYAzGZmAJlmZgBmZmYAM2ZmAABmZgD/M2YAzDNmAJkzZgBmM2YAMzNmAAAzZgD/AGYAzABmAJkAZgBmAGYAMwBmAAAAZgD//zMAzP8zAJn/MwBm/zMAM/8zAAD/MwD/zDMAzMwzAJnMMwBmzDMAM8wzAADMMwD/mTMAzJkzAJmZMwBmmTMAM5kzAACZMwD/ZjMAzGYzAJlmMwBmZjMAM2YzAABmMwD/MzMAzDMzAJkzMwBmMzMAMzMzAAAzMwD/ADMAzAAzAJkAMwBmADMAMwAzAAAAMwD//wAAzP8AAJn/AABm/wAAM/8AAAD/AAD/zAAAzMwAAJnMAABmzAAAM8wAAADMAAD/mQAAzJkAAJmZAABmmQAAM5kAAACZAAD/ZgAAzGYAAJlmAABmZgAAM2YAAABmAAD/MwAAzDMAAJkzAABmMwAAMzMAAAAzAAD/AAAAzAAAAJkAAABmAAAAMwAAAAAAAACflZYAl4iEAJF9dwBsPCAAyuH7AMTW7AC4wdEAsbTAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA29vb29vb29vb29vb29vb29vc3Nzc3Nzc3Nzc3Nzc3Nvb3Nvb29vb29vb29vb29zb29zb29vb29vb29vb29vc29vc29vb29vb29vb29vb3Nvb3Nvb29vb29vb29vb29zb29zc29vb29zb29zc3dvc29vc3Nvb29vc29vc297Y3Nvb3Nzc39vb3Nvb3NvZ39zb29zc29vb29zb29zb3Nrc29vc39/f2t/f39vf39nb3Nvb3Nvb29vb29vb29vb29zb29zb29vb29vb29vb29vc29vc29vb29vb29vb29vb3Nvb3Nzc3Nzc3Nzc3Nzc3Nzb29vb29vb29vb29vb29vb2wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="));
        file_put_contents(Zend_Registry::get('config')->favicons->path."a54d65cc8768f644533b8853e3dff821.png", base64_decode("iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAB3RJTUUH1AgeBQECNBMNcgAAAAlwSFlzAAALEgAACxIB0t1+/AAAAARnQU1BAACxjwv8YQUAAALESURBVHjajVNLTxNRGD3TGfqkT2pbjCSURzVCKa9EXMrCLSFGoglLw8adxoUrjf+h/4AQ0YWpOzcmJoqtxQUiIEgRA33QUuhrpnRmOtd7h5SIbriTO/ny3e+c795z7uWm78+kBYHc9Dl8YjQaLeICY25uzntcP7YqChfnpu/NEKJpsLfb36tEfeaxOnZ+Z7MOgee9f4M0oNDl81WPpEoPD/5FTazd4gwGCEajEblcDuVyedIfCEyW6+L80NBgv9VquWExW8FR8Il8Aqlej+/+2t0mGmbTuTQ0QhAIBCC0t9ujLmf9oSzL8Hg86Al2z46Pj+Fafwhul0cnqIhV/ExtTyQSXya2Uzsol0pgjRmWvx4Z/mYyGR85HQ4MR4YwOjICn+8STGYTmkoTDUpM6McAbrcbTbWJcqUCoa0Nqkbu8KPhsAwDV+rwem877Q7sp+n2VA1mqwUGA4emxgBlbGz8wOrqd5ozoKEoEEXxMa+oH/iVlRW1tz9EvN6OB2azGclkEgf5PIhG6E58kGlxPJ7Ax09L2NzaQuflTkiihGwm9/zlwsKucKYyFWVgYAC1Wo12WkWj0UDoaggcx2HpcxzFYhGRSAThcBiZbPbMHUMrYB0JJQkGg3A6nTg8PIRYE3VCFrNcMNiNZrMJjdr+H4GiKswqFAoF3VbmiKKqUOlkMcvl8wVUKaksK+cJVEIOJKn+LpPJ6J38fr9+HH1nBHrMcg7qVJqKzGoZhq3z7Le1vl7q7ult8AJ/t7evTy9mUxBOJbLZbLqgTpeLurGBTGb/aezV66VzR6Cnih8Vj+ZTqRR4nte9lxVZnyxmObZ2SGs0Yki0cHwr2Fxbq3T19SdqlcqVvb29QZPJpF8aSZJ0XZLLy0yDxeNK9cnbxcV0C8f9+9KmpqZcMJvtNovxDQE3dlpEvop1eRonJ9VYLFa6yIu98PgDflRkerhI7ucAAAAASUVORK5CYII="));
        file_put_contents(Zend_Registry::get('config')->favicons->path."d1e9f2ee7385eed7f85bae612ad9f8a7.ico", base64_decode("R0lGODlhEAAQAOYAAPr9/07H/3LT/xdZeAUUGzjA/3XT/57g/xA8UZzg/1rL/+T3/1/N/1XJ/3rV/wIHCTlUZTlWZwECAzlTY8ru/wsqOQ42SPj9/wwtPNXo8Lnp/xNKYxhce6Xj/11dXajj/4bZ/1FRUc/w/4HX/ztCSjaBpljK/yeWydby/yiazzZ4mDZ/oxplhy5rhzWFrDpLVzduizlZazlRYAomM/b8/8Ls/83v/y6z8DKt5jaCqMXt/zWHrzhieSOItzKz7yqh2DWIsfD7/5Dc/3zW/yWRwy+18/X8/hVQbDd1lBZVcjOq4kTE/+76/9/1/yEhIWbP/4ja/zpOXDdzkR92nzvB//z8/CB7pTSYxy6x7UnG/8zMzDG+/////wAAADs8QQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAQABAAAAe0gF6Cg4SFhoQQMRFRh4IyOz4mDAoBOCokhTlLH0xcnlwLQgWEQAY0XEE6CR0iF6CDLg6fAAJbtlQHXII8DQAAnxkcLES2BoJXNVw2n1pdzghYW14vWVwUCkZcVSHOz9IwI1wgWy0eTt3dPV4rCVxPWxXo6ANeJbkMWzPy3UleUlBchmzZsM+ZFS8TGnDRsCWFhH0EighS0gRAgC1THqAjcEKaFyQCuKAosOXHEQwWBtzYEiAQADs="));
        
        sleep(1);
        
        // update data
        $this->_forward('silent');
    }
}

