<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>rsslounge aggregator</title>
    
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="language" content="<?PHP echo Zend_Registry::get('session')->language ?>" />
    
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" media="screen, handheld, projection, tv" href="../stylesheets/style.css" />

</head>
<body>
    <!-- header -->
    <div id="header">
        <h1><span>rssLounge aggregator</span></h1>
    </div>
    

    <!-- main area -->
    <div id="ie">
        <?PHP echo $this->translate("This application doesn't support the Internet Explorer 6. Please install a newer Version, a Gecko or Webkit based or another modern Browser!"); ?>
        
        <ul>
            <li>
                <a href="http://www.mozilla-europe.org/de/firefox/">
                    <img src="../stylesheets/images/browser_firefox.png" alt="Mozilla Firefox" title="Mozilla Firefox" /><br/>
                    Mozilla Firefox
                </a>
            </li>
            <li>
                <a href="http://www.apple.com/de/safari/">
                    <img src="../stylesheets/images/browser_safari.png" alt="Safari" title="Safari" /><br/>
                    Safari
                </a>
            </li>
            <li>
                <a href="http://www.opera.com">
                    <img src="../stylesheets/images/browser_opera.png" alt="Opera" title="Opera" /><br/>
                    Opera
                </a>
            </li>
            <li>
                <a href="http://www.google.com/chrome">
                    <img src="../stylesheets/images/browser_chrome.png" alt="Chrome" title="Chrome" /><br/>
                    Chrome
                </a>
            </li>
        </ul>
    </div>

</body>
</html>