<?PHP 
    if(isset($this->multimedia))
        $imagelist = $this->render('item/multimedia.'.Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')->getViewSuffix());
    
    if(Zend_Registry::get('session')->imagesPosition=='top' && isset($this->multimedia) && count($this->multimedia)>0)
        echo $imagelist;
?>

<!-- text messages -->
<?PHP if(isset($this->messages) && count($this->messages)>0) : ?>
<ul id="messages">
    <?PHP
        if($this->search)
            for($i=0;$i<count($this->messages);$i++)
                $this->messages[$i]['search'] = $this->search;
        
        echo $this->partialLoop(
            'item/message-item.'.Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')->getViewSuffix(), 
            $this->messages
        );
    ?>
    <?PHP if($this->moreMessages) : ?>
    <li class="more"><span><?PHP echo $this->translate('more'); ?></span></li>
    <?PHP endif; ?>
</ul>
<?PHP endif; ?>

<?PHP 
    if(Zend_Registry::get('session')->imagesPosition=='bottom' && isset($this->multimedia) && count($this->multimedia)>0)
        echo $imagelist;
?>

<?PHP if(
        (!isset($this->messages) || count($this->messages)==0)
        && (!isset($this->multimedia) || count($this->multimedia)==0)
        ) : ?>
        
<div id="noentries">
    <?PHP echo $this->translate('No items found'); ?>
</div>
<?PHP endif; ?>