<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>rsslounge aggregator</title>
    
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" media="screen, handheld, projection, tv" href="stylesheets/style.css" />
    <link rel="stylesheet" media="screen, handheld, projection, tv" href="stylesheets/install.css" />
    
    <script type="text/javascript" src="javascript/jquery-1.3.2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){        
            $('#install').attr('action',document.location+'?execute=1');
        });
    </script>
</head>
<body>
    <!-- header -->
    <div id="header">
        <h1><span>rssLounge aggregator</span></h1>
    </div>
    

    <!-- main area -->
    <form id="install" action="" method="get">
        <h1><?PHP echo $this->translate('Update'); ?></h1>
        
        <?PHP echo $this->translate('The current rsslounge database is out of date. Click the button below for updating it.'); ?>
        <br /><br />
        <input type="hidden" name="execute" value="1" />
        <input type="submit" value="<?PHP echo $this->translate('update rsslounge') ?>" />
    </form>
</body>
</html>